apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd
  labels:
    app: httpd_webserver
    license: mit
spec:
  containers:
  - name: cntr-httpd
    image: httpd:latest
    ports:
    - containerPort: 80
    command: ["/bin/bash", "-c"]     # We have performed a command override here for testing purposes.
    args:
    - |
      /bin/echo "You've hit - $HOSTNAME" > /usr/local/apache2/htdocs/index.html
      /usr/local/bin/httpd-foreground  

