---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-data-storage 
spec:
  capacity:
    storage: 1Gi
  accessModes:         # this means that corresponding PV can only be used by a single node. Also see: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    - ReadWriteOnce
  nfs:
    path: /nfs/export_rw
    server: 10.3.5.109