---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-httpd
spec:
  replicas: 2 
  selector:
    matchLabels:
      component: httpd_webserver
  template:
    metadata:
      labels:
        component: httpd_webserver
    spec:
      volumes:
      - name: tls-files 
        secret:
          secretName: mysecret
      containers:
        - name: cntr-httpd
          image: httpd:latest
          volumeMounts:
            - name: httpd-tls
              mountPath: /usr/local/apache2/tls        # this folder will get created
              readOnly: true
          ports:
            - containerPort: 80
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update
              apt-get install -y curl
              /bin/echo "You've hit httpd - $HOSTNAME" > /usr/local/apache2/htdocs/index.html
              /usr/local/bin/httpd-foreground