apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podname
  name: podname
spec:
  containers:
  - image: nginx
    name: podname
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
