---
apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd
spec:
  containers:
    - name: cntr-httpd
      image: https://index.docker.io/v1/codingbee/httpd:0.1
      ports:
        - containerPort: 80