apiVersion: v1
kind: Service
metadata:
  name: svc-clusterip-caddy
  namespace: codingbee         # notice that you have to specify the namespace to get the correct dns entry setup
spec:
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: 2015
  selector:
    component: caddy_pod