apiVersion: v1
kind: Pod
metadata:
  name: pod-ubi
spec: 
  containers:
  - name: cntr-ubi
    image: centos
    command: ["/bin/bash", "-c"]
    args:
    - |
      while true ; do
        date 
        sleep 5 
      done