---
apiVersion: v1
kind: Pod
metadata:
  name: pod-centos
spec: 
  serviceAccountName: basic-access     # We add this line. 
  containers:
    - name: cntr-centos
      image: centos
      command: ["/bin/bash", "-c"]
      args:
        - |
          while true ; do
            date 
            sleep 10 
          done