---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: employees
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: employee-role
subjects:
  - kind: Group
    name: employee
    namespace: default
