---
apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd
  namespace: codingbee-hello-world       # we add this line. 
  labels:
    app: apache_webserver
spec: 
  containers:
    - name: cntr-httpd
      image: httpd
      ports:
        - containerPort: 80