apiVersion: v1
kind: Pod
metadata:
  name: pod-2cntrs
  labels:
    cntr1: apache_webserver
    cntr2: centos
spec:
  containers:
  - name: cntr-httpd
    image: httpd:latest
    ports:
    - containerPort: 80
  - name: cntr-centos
    image: centos
    command: ["/bin/bash", "-c"]
    args:
    - |
      while true ; do
        date
        curl http://127.0.0.1
        sleep 5 
      done