---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-read
  namespace: default    # This is mandatory, if omitted then 'default' is used
rules:
  - apiGroups: [""] 
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] 
    resources: ["services"]
    verbs: ["get", "watch", "list"]
