apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-httpd
  name: pod-httpd
spec:
  containers:
  - image: httpd
    name: pod-httpd
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
