apiVersion: v1
kind: Pod
metadata:
  name: pod-centos
  labels:
    app: healthchecker
spec:
  containers:
    - name: cntr-centos
      image: centos
      command: ["/bin/bash", "-c"]
      args:
        - |
          while true ; do
            date
            curl -s --connect-timeout 10 http://svc-clusterip-httpd.default.svc.cluster.local 2>&1
            sleep 10
          done