apiVersion: v1
kind: Pod
metadata:
  name: pod-multi-cntr
  labels:
    cntr1: apache_webserver
    cntr2: centos
spec:
  containers:
  - name: cntr-httpd
    image: httpd:latest
    ports:
    - containerPort: 80
  - name: cntr-centos
    image: centos
    command: ["/bin/bash", "-c"]
    args:
    - |
      while true ; do
        date
        curl http://localhost 
        sleep 5 
      done